controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

homepage:
    path: /
    controller: App\Controller\AdminController::index

catch_all:
    path: /{url}
    defaults:
        _controller: App\Controller\AdminController::index
    requirements:
        url: .*